version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper 
    port:
      - 2181:2181
  kafka: 
    container_name: kafka
    image: wurstmeister/zookeeper 
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock 
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  mango:
    container_name: mongo
    image: mongo
    ports:
       - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgres/data 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
